# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The First Half of Ziyi's Life  --  菜懿的前半生 来不及解释了，快上车:)
email: troppingz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where part my thoughts goes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  Tr0py

# Build settings
markdown: kramdown
